
name: PR Workflow

on:
  pull_request:
    branches:
      - '**'

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build with Gradle, run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            check 
            -x jacocoTestCoverageVerification 
            -x jacocoTestReport
